version: '2'

services:
    mysql-dashboard:
        container_name: expense_tracker_musql
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
          - ./docker/mysql/init-sql:/docker-entrypoint-initdb.d:ro
        environment:
          - MYSQL_USER=docker
          - MYSQL_PASSWORD=letmein
          - MYSQL_DATABASE=expense_tracker_musql
          - MYSQL_ROOT_PASSWORD=docker


